live_config_reload = true

import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Transparent"
dynamic_padding = false
opacity = 0.9
blur = true
startup_mode = "Maximized"

[window.padding]
x = 25
y = 20

[font]
size = 15.0

[font.bold]
# family = "Consolas ligaturized v3"
# style = "Book"
# family = "FiraCode Nerd Font"
family = "MonoLisaNerdFontCompleteMono Nerd Font"
style = "Bold"
#style = "Regular"

[font.bold_italic]
# family = "Consolas NF"
#family = "Consolas ligaturized v3"
#style = "Regular"
# family = "FiraCode Nerd Font"
family = "MonoLisaNerdFontCompleteMono Nerd Font"
style = "Bold Italic"


[font.normal]
# family = "Consolas NF"
#family = "Consolas ligaturized v3"
# style = "Book"
# family = "FiraCode Nerd Font"
style = "Regular"
family = "MonoLisaNerdFontCompleteMono Nerd Font"


[font.italic]
# family = "Consolas NF"
#family = "Consolas ligaturized v3"
#style = "Italic"
# style = "Book"
# family = "FiraCode Nerd Font"
style = "Italic"
family = "MonoLisaNerdFontCompleteMono Nerd Font"


